import { forwardRef } from "react";
import "../components/Printable.scss";
import Letterhead from "./Letterhead";

interface PrintableProps {
  content: string | undefined;
  patient: any;
  ref?: React.Ref<HTMLDivElement>;
}
const Printable = forwardRef<HTMLDivElement, PrintableProps>(
  ({ content, patient }, ref) => {
    return (
      <>
        <div ref={ref} className="printable-container">
          <Letterhead />
          <hr />
          <div className="patient-info">
            <table>
              <tbody>
                <tr>
                  <td>Patient Name:</td>
                  <td>{patient?.patient_name || "Not Specified"}</td>
                </tr>
                <tr>
                  <td>Patient ID:</td>
                  <td>{patient?.patient_id || "Not Specified"}</td>
                </tr>
                <tr>
                  <td>Gender:</td>
                  <td>{patient?.gender || "Not Specified"}</td>
                </tr>
                <tr>
                  <td>Date of Birth:</td>
                  <td>{patient?.dob || "Not Specified"}</td>
                </tr>
                <tr>
                  <td>Examination:</td>
                  <td>{patient?.examination || "Not Specified"}</td>
                </tr>
                <tr>
                  <td>Examination Date:</td>
                  <td>{patient?.study_date || "Not Specified"}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <hr />
          <div dangerouslySetInnerHTML={{ __html: content || "" }} />

          <footer>
            <p>GENERATED BY: {patient?.radiologist_name.toUpperCase()} </p>
          </footer>
        </div>
      </>
    );
  },
);

export default Printable;
